name: "UnionSpace"
alias: "GRF1.0+GRF2.0_P"
params:
  - name: "GRF"
    params:
      length_scale: 2.0
      kernal: ExpSineSquared
  - name: "GRF"
    params:
      length_scale: 1.0
      kernal: ExpSineSquared
